// Vue_Full_Project/src/views/components/SocialButtons.vue
<template>
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-12">
        <b-card>
          <div slot="header">
            <strong>Social Media Button</strong> <small>Usage ex.</small><code style="text-transform:lowercase">&lt;b-button variant="facebook"&gt;&lt;span&gt;Facebook&lt;/span&gt;&lt;/b-button&gt;</code>
          </div>
          <h6>Size Small <small>Add this <code>size="sm"</code></small></h6>
          <p>
            <b-button size="sm" variant="facebook"><span>Facebook</span></b-button>
            <b-button size="sm" variant="twitter"><span>Twitter</span></b-button>
            <b-button size="sm" variant="linkedin"><span>LinkedIn</span></b-button>
            <b-button size="sm" variant="flickr"><span>Flickr</span></b-button>
            <b-button size="sm" variant="tumblr"><span>Tumblr</span></b-button>
            <b-button size="sm" variant="xing"><span>Xing</span></b-button>
            <b-button size="sm" variant="github"><span>Github</span></b-button>
            <b-button size="sm" variant="html5"><span>HTML5</span></b-button>
            <b-button size="sm" variant="openid"><span>OpenID</span></b-button>
            <b-button size="sm" variant="stack-overflow"><span>StackOverflow</span></b-button>
            <b-button size="sm" variant="css3"><span>CSS3</span></b-button>
            <b-button size="sm" variant="youtube"><span>YouTube</span></b-button>
            <b-button size="sm" variant="dribbble"><span>Dribbble</span></b-button>
            <b-button size="sm" variant="google-plus"><span>Google+</span></b-button>
            <b-button size="sm" variant="instagram"><span>Instagram</span></b-button>
            <b-button size="sm" variant="pinterest"><span>Pinterest</span></b-button>
            <b-button size="sm" variant="vk"><span>VK</span></b-button>
            <b-button size="sm" variant="yahoo"><span>Yahoo</span></b-button>
            <b-button size="sm" variant="behance"><span>Behance</span></b-button>
            <b-button size="sm" variant="dropbox"><span>Dropbox</span></b-button>
            <b-button size="sm" variant="reddit"><span>Reddit</span></b-button>
            <b-button size="sm" variant="spotify"><span>Spotify</span></b-button>
            <b-button size="sm" variant="vine"><span>Vine</span></b-button>
            <b-button size="sm" variant="foursquare"><span>Forsquare</span></b-button>
            <b-button size="sm" variant="vimeo"><span>Vimeo</span></b-button>
          </p>
          <h6>Size Normal</h6>
          <p>
            <b-button variant="facebook"><span>Facebook</span></b-button>
            <b-button variant="twitter"><span>Twitter</span></b-button>
            <b-button variant="linkedin"><span>LinkedIn</span></b-button>
            <b-button variant="flickr"><span>Flickr</span></b-button>
            <b-button variant="tumblr"><span>Tumblr</span></b-button>
            <b-button variant="xing"><span>Xing</span></b-button>
            <b-button variant="github"><span>Github</span></b-button>
            <b-button variant="html5"><span>HTML5</span></b-button>
            <b-button variant="openid"><span>OpenID</span></b-button>
            <b-button variant="stack-overflow"><span>StackOverflow</span></b-button>
            <b-button variant="css3"><span>CSS3</span></b-button>
            <b-button variant="youtube"><span>YouTube</span></b-button>
            <b-button variant="dribbble"><span>Dribbble</span></b-button>
            <b-button variant="google-plus"><span>Google+</span></b-button>
            <b-button variant="instagram"><span>Instagram</span></b-button>
            <b-button variant="pinterest"><span>Pinterest</span></b-button>
            <b-button variant="vk"><span>VK</span></b-button>
            <b-button variant="yahoo"><span>Yahoo</span></b-button>
            <b-button variant="behance"><span>Behance</span></b-button>
            <b-button variant="dropbox"><span>Dropbox</span></b-button>
            <b-button variant="reddit"><span>Reddit</span></b-button>
            <b-button variant="spotify"><span>Spotify</span></b-button>
            <b-button variant="vine"><span>Vine</span></b-button>
            <b-button variant="foursquare"><span>Forsquare</span></b-button>
            <b-button variant="vimeo"><span>Vimeo</span></b-button>
          </p>
          <h6>Size Large <small>Add this <code>size="lg"</code></small></h6>
          <p>
            <b-button size="lg" variant="facebook"><span>Facebook</span></b-button>
            <b-button size="lg" variant="twitter"><span>Twitter</span></b-button>
            <b-button size="lg" variant="linkedin"><span>LinkedIn</span></b-button>
            <b-button size="lg" variant="flickr"><span>Flickr</span></b-button>
            <b-button size="lg" variant="tumblr"><span>Tumblr</span></b-button>
            <b-button size="lg" variant="xing"><span>Xing</span></b-button>
            <b-button size="lg" variant="github"><span>Github</span></b-button>
            <b-button size="lg" variant="html5"><span>HTML5</span></b-button>
            <b-button size="lg" variant="openid"><span>OpenID</span></b-button>
            <b-button size="lg" variant="stack-overflow"><span>StackOverflow</span></b-button>
            <b-button size="lg" variant="css3"><span>CSS3</span></b-button>
            <b-button size="lg" variant="youtube"><span>YouTube</span></b-button>
            <b-button size="lg" variant="dribbble"><span>Dribbble</span></b-button>
            <b-button size="lg" variant="google-plus"><span>Google+</span></b-button>
            <b-button size="lg" variant="instagram"><span>Instagram</span></b-button>
            <b-button size="lg" variant="pinterest"><span>Pinterest</span></b-button>
            <b-button size="lg" variant="vk"><span>VK</span></b-button>
            <b-button size="lg" variant="yahoo"><span>Yahoo</span></b-button>
            <b-button size="lg" variant="behance"><span>Behance</span></b-button>
            <b-button size="lg" variant="dropbox"><span>Dropbox</span></b-button>
            <b-button size="lg" variant="reddit"><span>Reddit</span></b-button>
            <b-button size="lg" variant="spotify"><span>Spotify</span></b-button>
            <b-button size="lg" variant="vine"><span>Vine</span></b-button>
            <b-button size="lg" variant="foursquare"><span>Forsquare</span></b-button>
            <b-button size="lg" variant="vimeo"><span>Vimeo</span></b-button>
          </p>
        </b-card>
      </div><!--/.col-->
      <div class="col-12">
        <b-card>
          <div slot="header">
            <strong>Social Media Button</strong> <small>Only icons. Usage ex.</small> <code style="text-transform:lowercase">&lt;b-button variant="facebook icon"&gt;&lt;span&gt;Facebook&lt;/span&gt;&lt;/b-button&gt;</code>
          </div>
          <h6>Size Small <small>Add this <code>size="sm"</code></small></h6>
          <p>
            <b-button size="sm" variant="facebook icon"></b-button>
            <b-button size="sm" variant="twitter icon"></b-button>
            <b-button size="sm" variant="linkedin icon"></b-button>
            <b-button size="sm" variant="flickr icon"></b-button>
            <b-button size="sm" variant="tumblr icon"></b-button>
            <b-button size="sm" variant="xing icon"></b-button>
            <b-button size="sm" variant="github icon"></b-button>
            <b-button size="sm" variant="html5 icon"></b-button>
            <b-button size="sm" variant="openid icon"></b-button>
            <b-button size="sm" variant="stack-overflow icon"></b-button>
            <b-button size="sm" variant="css3 icon"></b-button>
            <b-button size="sm" variant="youtube icon"></b-button>
            <b-button size="sm" variant="dribbble icon"></b-button>
            <b-button size="sm" variant="google-plus icon"></b-button>
            <b-button size="sm" variant="instagram icon"></b-button>
            <b-button size="sm" variant="pinterest icon"></b-button>
            <b-button size="sm" variant="vk icon"></b-button>
            <b-button size="sm" variant="yahoo icon"></b-button>
            <b-button size="sm" variant="behance icon"></b-button>
            <b-button size="sm" variant="dropbox icon"></b-button>
            <b-button size="sm" variant="reddit icon"></b-button>
            <b-button size="sm" variant="spotify icon"></b-button>
            <b-button size="sm" variant="vine icon"></b-button>
            <b-button size="sm" variant="foursquare icon"></b-button>
            <b-button size="sm" variant="vimeo icon"></b-button>
          </p>
          <h6>Size Normal</h6>
          <p>
            <b-button variant="facebook icon"></b-button>
            <b-button variant="twitter icon"></b-button>
            <b-button variant="linkedin icon"></b-button>
            <b-button variant="flickr icon"></b-button>
            <b-button variant="tumblr icon"></b-button>
            <b-button variant="xing icon"></b-button>
            <b-button variant="github icon"></b-button>
            <b-button variant="html5 icon"></b-button>
            <b-button variant="openid icon"></b-button>
            <b-button variant="stack-overflow icon"></b-button>
            <b-button variant="css3 icon"></b-button>
            <b-button variant="youtube icon"></b-button>
            <b-button variant="dribbble icon"></b-button>
            <b-button variant="google-plus icon"></b-button>
            <b-button variant="instagram icon"></b-button>
            <b-button variant="pinterest icon"></b-button>
            <b-button variant="vk icon"></b-button>
            <b-button variant="yahoo icon"></b-button>
            <b-button variant="behance icon"></b-button>
            <b-button variant="dropbox icon"></b-button>
            <b-button variant="reddit icon"></b-button>
            <b-button variant="spotify icon"></b-button>
            <b-button variant="vine icon"></b-button>
            <b-button variant="foursquare icon"></b-button>
            <b-button variant="vimeo icon"></b-button>
          </p>
          <h6>Size Large <small>Add this <code>size="lg"</code></small></h6>
          <p>
            <b-button size="lg" variant="facebook icon"><span>Facebook</span></b-button>
            <b-button size="lg" variant="twitter icon"><span>Twitter</span></b-button>
            <b-button size="lg" variant="linkedin icon"><span>LinkedIn</span></b-button>
            <b-button size="lg" variant="flickr icon"><span>Flickr</span></b-button>
            <b-button size="lg" variant="tumblr icon"><span>Tumblr</span></b-button>
            <b-button size="lg" variant="xing icon"><span>Xing</span></b-button>
            <b-button size="lg" variant="github icon"><span>Github</span></b-button>
            <b-button size="lg" variant="html5 icon"><span>HTML5</span></b-button>
            <b-button size="lg" variant="openid icon"><span>OpenID</span></b-button>
            <b-button size="lg" variant="stack-overflow icon"><span>StackOverflow</span></b-button>
            <b-button size="lg" variant="css3 icon"><span>CSS3</span></b-button>
            <b-button size="lg" variant="youtube icon"><span>YouTube</span></b-button>
            <b-button size="lg" variant="dribbble icon"><span>Dribbble</span></b-button>
            <b-button size="lg" variant="google-plus icon"><span>Google+</span></b-button>
            <b-button size="lg" variant="instagram icon"><span>Instagram</span></b-button>
            <b-button size="lg" variant="pinterest icon"><span>Pinterest</span></b-button>
            <b-button size="lg" variant="vk icon"><span>VK</span></b-button>
            <b-button size="lg" variant="yahoo icon"><span>Yahoo</span></b-button>
            <b-button size="lg" variant="behance icon"><span>Behance</span></b-button>
            <b-button size="lg" variant="dropbox icon"><span>Dropbox</span></b-button>
            <b-button size="lg" variant="reddit icon"><span>Reddit</span></b-button>
            <b-button size="lg" variant="spotify icon"><span>Spotify</span></b-button>
            <b-button size="lg" variant="vine icon"><span>Vine</span></b-button>
            <b-button size="lg" variant="foursquare icon"><span>Forsquare</span></b-button>
            <b-button size="lg" variant="vimeo icon"><span>Vimeo</span></b-button>
          </p>
        </b-card>
      </div><!--/.col-->

      <div class="col-12">
        <b-card>
          <div slot="header">
            <strong>Social Media Button</strong> <small>Only text. Usage ex.</small> <code style="text-transform:lowercase">&lt;b-button variant="facebook text"&gt;&lt;span&gt;Facebook&lt;/span&gt;&lt;/b-button&gt;</code>
          </div>
          <h6>Size Small <small>Add this <code>size="sm"</code></small></h6>
          <p>
            <b-button size="sm" variant="facebook text"><span>Facebook</span></b-button>
            <b-button size="sm" variant="twitter text"><span>Twitter</span></b-button>
            <b-button size="sm" variant="linkedin text"><span>LinkedIn</span></b-button>
            <b-button size="sm" variant="flickr text"><span>Flickr</span></b-button>
            <b-button size="sm" variant="tumblr text"><span>Tumblr</span></b-button>
            <b-button size="sm" variant="xing text"><span>Xing</span></b-button>
            <b-button size="sm" variant="github text"><span>Github</span></b-button>
            <b-button size="sm" variant="html5 text"><span>HTML5</span></b-button>
            <b-button size="sm" variant="openid text"><span>OpenID</span></b-button>
            <b-button size="sm" variant="stack-overflow text"><span>StackOverflow</span></b-button>
            <b-button size="sm" variant="css3 text"><span>CSS3</span></b-button>
            <b-button size="sm" variant="youtube text"><span>YouTube</span></b-button>
            <b-button size="sm" variant="dribbble text"><span>Dribbble</span></b-button>
            <b-button size="sm" variant="google-plus text"><span>Google+</span></b-button>
            <b-button size="sm" variant="instagram text"><span>Instagram</span></b-button>
            <b-button size="sm" variant="pinterest text"><span>Pinterest</span></b-button>
            <b-button size="sm" variant="vk text"><span>VK</span></b-button>
            <b-button size="sm" variant="yahoo text"><span>Yahoo</span></b-button>
            <b-button size="sm" variant="behance text"><span>Behance</span></b-button>
            <b-button size="sm" variant="dropbox text"><span>Dropbox</span></b-button>
            <b-button size="sm" variant="reddit text"><span>Reddit</span></b-button>
            <b-button size="sm" variant="spotify text"><span>Spotify</span></b-button>
            <b-button size="sm" variant="vine text"><span>Vine</span></b-button>
            <b-button size="sm" variant="foursquare text"><span>Forsquare</span></b-button>
            <b-button size="sm" variant="vimeo text"><span>Vimeo</span></b-button>
          </p>
          <h6>Size Normal</h6>
          <p>
            <b-button variant="facebook text"><span>Facebook</span></b-button>
            <b-button variant="twitter text"><span>Twitter</span></b-button>
            <b-button variant="linkedin text"><span>LinkedIn</span></b-button>
            <b-button variant="flickr text"><span>Flickr</span></b-button>
            <b-button variant="tumblr text"><span>Tumblr</span></b-button>
            <b-button variant="xing text"><span>Xing</span></b-button>
            <b-button variant="github text"><span>Github</span></b-button>
            <b-button variant="html5 text"><span>HTML5</span></b-button>
            <b-button variant="openid text"><span>OpenID</span></b-button>
            <b-button variant="stack-overflow text"><span>StackOverflow</span></b-button>
            <b-button variant="css3 text"><span>CSS3</span></b-button>
            <b-button variant="youtube text"><span>YouTube</span></b-button>
            <b-button variant="dribbble text"><span>Dribbble</span></b-button>
            <b-button variant="google-plus text"><span>Google+</span></b-button>
            <b-button variant="instagram text"><span>Instagram</span></b-button>
            <b-button variant="pinterest text"><span>Pinterest</span></b-button>
            <b-button variant="vk text"><span>VK</span></b-button>
            <b-button variant="yahoo text"><span>Yahoo</span></b-button>
            <b-button variant="behance text"><span>Behance</span></b-button>
            <b-button variant="dropbox text"><span>Dropbox</span></b-button>
            <b-button variant="reddit text"><span>Reddit</span></b-button>
            <b-button variant="spotify text"><span>Spotify</span></b-button>
            <b-button variant="vine text"><span>Vine</span></b-button>
            <b-button variant="foursquare text"><span>Forsquare</span></b-button>
            <b-button variant="vimeo text"><span>Vimeo</span></b-button>
          </p>
          <h6>Size Large <small>Add this <code>size="lg"</code></small></h6>
          <p>
            <b-button size="lg" variant="facebook text"><span>Facebook</span></b-button>
            <b-button size="lg" variant="twitter text"><span>Twitter</span></b-button>
            <b-button size="lg" variant="linkedin text"><span>LinkedIn</span></b-button>
            <b-button size="lg" variant="flickr text"><span>Flickr</span></b-button>
            <b-button size="lg" variant="tumblr text"><span>Tumblr</span></b-button>
            <b-button size="lg" variant="xing text"><span>Xing</span></b-button>
            <b-button size="lg" variant="github text"><span>Github</span></b-button>
            <b-button size="lg" variant="html5 text"><span>HTML5</span></b-button>
            <b-button size="lg" variant="openid text"><span>OpenID</span></b-button>
            <b-button size="lg" variant="stack-overflow text"><span>StackOverflow</span></b-button>
            <b-button size="lg" variant="css3 text"><span>CSS3</span></b-button>
            <b-button size="lg" variant="youtube text"><span>YouTube</span></b-button>
            <b-button size="lg" variant="dribbble text"><span>Dribbble</span></b-button>
            <b-button size="lg" variant="google-plus text"><span>Google+</span></b-button>
            <b-button size="lg" variant="instagram text"><span>Instagram</span></b-button>
            <b-button size="lg" variant="pinterest text"><span>Pinterest</span></b-button>
            <b-button size="lg" variant="vk text"><span>VK</span></b-button>
            <b-button size="lg" variant="yahoo text"><span>Yahoo</span></b-button>
            <b-button size="lg" variant="behance text"><span>Behance</span></b-button>
            <b-button size="lg" variant="dropbox text"><span>Dropbox</span></b-button>
            <b-button size="lg" variant="reddit text"><span>Reddit</span></b-button>
            <b-button size="lg" variant="spotify text"><span>Spotify</span></b-button>
            <b-button size="lg" variant="vine text"><span>Vine</span></b-button>
            <b-button size="lg" variant="foursquare text"><span>Forsquare</span></b-button>
            <b-button size="lg" variant="vimeo text"><span>Vimeo</span></b-button>
          </p>
        </b-card>
      </div><!--/.col-->
    </div><!--/.row-->
  </div>
</template>

<script>
export default {
  name: 'social-buttons'
}
</script>

<style scoped lang="css">
.btn {
  margin-bottom: 4px;
}
</style>

// demo/pro/React_Demo/src/views/Components/SocialButtons/SocialButtons.js
import React, {Component} from "react";
import {Row, Col, Card, CardHeader, CardBlock, Button} from "reactstrap";

class SocialButtons extends Component {
  render() {
    return (
      <div className="animated fadeIn">
        <Row>
          <Col xs="12">
            <Card>
              <CardHeader>
                <strong>Social Media Button</strong>
                <small>Usage ex.</small>
                <code style={{textTransform: 'lowercase'}}>&lt;button className="btn-facebook"&gt;&lt;span&gt;
                  Facebook&lt;/span&gt;&lt;/Button&gt;</code>
              </CardHeader>
              <CardBlock className="card-body">
                <h6>Size Small
                  <small>Add this class <code>.btn-sm</code></small>
                </h6>
                <p>
                  <Button size="sm" className="btn-facebook"><span>Facebook</span></Button>
                  <Button size="sm" className="btn-twitter"><span>Twitter</span></Button>
                  <Button size="sm" className="btn-linkedin"><span>LinkedIn</span></Button>
                  <Button size="sm" className="btn-flickr"><span>Flickr</span></Button>
                  <Button size="sm" className="btn-tumblr"><span>Tumblr</span></Button>
                  <Button size="sm" className="btn-xing"><span>Xing</span></Button>
                  <Button size="sm" className="btn-github"><span>Github</span></Button>
                  <Button size="sm" className="btn-html5"><span>HTML5</span></Button>
                  <Button size="sm" className="btn-openid"><span>OpenID</span></Button>
                  <Button size="sm" className="btn-stack-overflow"><span>StackOverflow</span></Button>
                  <Button size="sm" className="btn-css3"><span>CSS3</span></Button>
                  <Button size="sm" className="btn-youtube"><span>YouTube</span></Button>
                  <Button size="sm" className="btn-dribbble"><span>Dribbble</span></Button>
                  <Button size="sm" className="btn-google-plus"><span>Google+</span></Button>
                  <Button size="sm" className="btn-instagram"><span>Instagram</span></Button>
                  <Button size="sm" className="btn-pinterest"><span>Pinterest</span></Button>
                  <Button size="sm" className="btn-vk"><span>VK</span></Button>
                  <Button size="sm" className="btn-yahoo"><span>Yahoo</span></Button>
                  <Button size="sm" className="btn-behance"><span>Behance</span></Button>
                  <Button size="sm" className="btn-dropbox"><span>Dropbox</span></Button>
                  <Button size="sm" className="btn-reddit"><span>Reddit</span></Button>
                  <Button size="sm" className="btn-spotify"><span>Spotify</span></Button>
                  <Button size="sm" className="btn-vine"><span>Vine</span></Button>
                  <Button size="sm" className="btn-foursquare"><span>Forsquare</span></Button>
                  <Button size="sm" className="btn-vimeo"><span>Vimeo</span></Button>
                </p>
                <h6>Size Normal</h6>
                <p>
                  <Button className="btn-facebook"><span>Facebook</span></Button>
                  <Button className="btn-twitter"><span>Twitter</span></Button>
                  <Button className="btn-linkedin"><span>LinkedIn</span></Button>
                  <Button className="btn-flickr"><span>Flickr</span></Button>
                  <Button className="btn-tumblr"><span>Tumblr</span></Button>
                  <Button className="btn-xing"><span>Xing</span></Button>
                  <Button className="btn-github"><span>Github</span></Button>
                  <Button className="btn-html5"><span>HTML5</span></Button>
                  <Button className="btn-openid"><span>OpenID</span></Button>
                  <Button className="btn-stack-overflow"><span>StackOverflow</span></Button>
                  <Button className="btn-css3"><span>CSS3</span></Button>
                  <Button className="btn-youtube"><span>YouTube</span></Button>
                  <Button className="btn-dribbble"><span>Dribbble</span></Button>
                  <Button className="btn-google-plus"><span>Google+</span></Button>
                  <Button className="btn-instagram"><span>Instagram</span></Button>
                  <Button className="btn-pinterest"><span>Pinterest</span></Button>
                  <Button className="btn-vk"><span>VK</span></Button>
                  <Button className="btn-yahoo"><span>Yahoo</span></Button>
                  <Button className="btn-behance"><span>Behance</span></Button>
                  <Button className="btn-dropbox"><span>Dropbox</span></Button>
                  <Button className="btn-reddit"><span>Reddit</span></Button>
                  <Button className="btn-spotify"><span>Spotify</span></Button>
                  <Button className="btn-vine"><span>Vine</span></Button>
                  <Button className="btn-foursquare"><span>Forsquare</span></Button>
                  <Button className="btn-vimeo"><span>Vimeo</span></Button>
                </p>
                <h6>Size Large
                  <small>Add this class <code>.btn-lg</code></small>
                </h6>
                <p>
                  <Button size="lg" className="btn-facebook"><span>Facebook</span></Button>
                  <Button size="lg" className="btn-twitter"><span>Twitter</span></Button>
                  <Button size="lg" className="btn-linkedin"><span>LinkedIn</span></Button>
                  <Button size="lg" className="btn-flickr"><span>Flickr</span></Button>
                  <Button size="lg" className="btn-tumblr"><span>Tumblr</span></Button>
                  <Button size="lg" className="btn-xing"><span>Xing</span></Button>
                  <Button size="lg" className="btn-github"><span>Github</span></Button>
                  <Button size="lg" className="btn-html5"><span>HTML5</span></Button>
                  <Button size="lg" className="btn-openid"><span>OpenID</span></Button>
                  <Button size="lg" className="btn-stack-overflow"><span>StackOverflow</span></Button>
                  <Button size="lg" className="btn-css3"><span>CSS3</span></Button>
                  <Button size="lg" className="btn-youtube"><span>YouTube</span></Button>
                  <Button size="lg" className="btn-dribbble"><span>Dribbble</span></Button>
                  <Button size="lg" className="btn-google-plus"><span>Google+</span></Button>
                  <Button size="lg" className="btn-instagram"><span>Instagram</span></Button>
                  <Button size="lg" className="btn-pinterest"><span>Pinterest</span></Button>
                  <Button size="lg" className="btn-vk"><span>VK</span></Button>
                  <Button size="lg" className="btn-yahoo"><span>Yahoo</span></Button>
                  <Button size="lg" className="btn-behance"><span>Behance</span></Button>
                  <Button size="lg" className="btn-dropbox"><span>Dropbox</span></Button>
                  <Button size="lg" className="btn-reddit"><span>Reddit</span></Button>
                  <Button size="lg" className="btn-spotify"><span>Spotify</span></Button>
                  <Button size="lg" className="btn-vine"><span>Vine</span></Button>
                  <Button size="lg" className="btn-foursquare"><span>Forsquare</span></Button>
                  <Button size="lg" className="btn-vimeo"><span>Vimeo</span></Button>
                </p>
              </CardBlock>
            </Card>
          </Col>

          <Col xs="12">
            <Card>
              <CardHeader>
                <strong>Social Media Button</strong>
                <small>Only icons. Usage ex.</small>
                <code style={{textTransform: 'lowercase'}}>&lt;button className="btn-facebook icon"&gt;&lt;span&gt;
                  Facebook&lt;/span&gt;&lt;/Button&gt;</code>
              </CardHeader>
              <CardBlock className="card-body">
                <h6>Size Small
                  <small>Add this class <code>.btn-sm</code></small>
                </h6>
                <p>
                  <Button size="sm" className="btn-facebook icon"><span>Facebook</span></Button>
                  <Button size="sm" className="btn-twitter icon"><span>Twitter</span></Button>
                  <Button size="sm" className="btn-linkedin icon"><span>LinkedIn</span></Button>
                  <Button size="sm" className="btn-flickr icon"><span>Flickr</span></Button>
                  <Button size="sm" className="btn-tumblr icon"><span>Tumblr</span></Button>
                  <Button size="sm" className="btn-xing icon"><span>Xing</span></Button>
                  <Button size="sm" className="btn-github icon"><span>Github</span></Button>
                  <Button size="sm" className="btn-html5 icon"><span>HTML5</span></Button>
                  <Button size="sm" className="btn-openid icon"><span>OpenID</span></Button>
                  <Button size="sm" className="btn-stack-overflow icon"><span>StackOverflow</span></Button>
                  <Button size="sm" className="btn-css3 icon"><span>CSS3</span></Button>
                  <Button size="sm" className="btn-youtube icon"><span>YouTube</span></Button>
                  <Button size="sm" className="btn-dribbble icon"><span>Dribbble</span></Button>
                  <Button size="sm" className="btn-google-plus icon"><span>Google+</span></Button>
                  <Button size="sm" className="btn-instagram icon"><span>Instagram</span></Button>
                  <Button size="sm" className="btn-pinterest icon"><span>Pinterest</span></Button>
                  <Button size="sm" className="btn-vk icon"><span>VK</span></Button>
                  <Button size="sm" className="btn-yahoo icon"><span>Yahoo</span></Button>
                  <Button size="sm" className="btn-behance icon"><span>Behance</span></Button>
                  <Button size="sm" className="btn-dropbox icon"><span>Dropbox</span></Button>
                  <Button size="sm" className="btn-reddit icon"><span>Reddit</span></Button>
                  <Button size="sm" className="btn-spotify icon"><span>Spotify</span></Button>
                  <Button size="sm" className="btn-vine icon"><span>Vine</span></Button>
                  <Button size="sm" className="btn-foursquare icon"><span>Forsquare</span></Button>
                  <Button size="sm" className="btn-vimeo icon"><span>Vimeo</span></Button>
                </p>
                <h6>Size Normal</h6>
                <p>
                  <Button className="btn-facebook icon"><span>Facebook</span></Button>
                  <Button className="btn-twitter icon"><span>Twitter</span></Button>
                  <Button className="btn-linkedin icon"><span>LinkedIn</span></Button>
                  <Button className="btn-flickr icon"><span>Flickr</span></Button>
                  <Button className="btn-tumblr icon"><span>Tumblr</span></Button>
                  <Button className="btn-xing icon"><span>Xing</span></Button>
                  <Button className="btn-github icon"><span>Github</span></Button>
                  <Button className="btn-html5 icon"><span>HTML5</span></Button>
                  <Button className="btn-openid icon"><span>OpenID</span></Button>
                  <Button className="btn-stack-overflow icon"><span>StackOverflow</span></Button>
                  <Button className="btn-css3 icon"><span>CSS3</span></Button>
                  <Button className="btn-youtube icon"><span>YouTube</span></Button>
                  <Button className="btn-dribbble icon"><span>Dribbble</span></Button>
                  <Button className="btn-google-plus icon"><span>Google+</span></Button>
                  <Button className="btn-instagram icon"><span>Instagram</span></Button>
                  <Button className="btn-pinterest icon"><span>Pinterest</span></Button>
                  <Button className="btn-vk icon"><span>VK</span></Button>
                  <Button className="btn-yahoo icon"><span>Yahoo</span></Button>
                  <Button className="btn-behance icon"><span>Behance</span></Button>
                  <Button className="btn-dropbox icon"><span>Dropbox</span></Button>
                  <Button className="btn-reddit icon"><span>Reddit</span></Button>
                  <Button className="btn-spotify icon"><span>Spotify</span></Button>
                  <Button className="btn-vine icon"><span>Vine</span></Button>
                  <Button className="btn-foursquare icon"><span>Forsquare</span></Button>
                  <Button className="btn-vimeo icon"><span>Vimeo</span></Button>
                </p>
                <h6>Size Large
                  <small>Add this class <code>.btn-lg</code></small>
                </h6>
                <p>
                  <Button size="lg" className="btn-facebook icon"><span>Facebook</span></Button>
                  <Button size="lg" className="btn-twitter icon"><span>Twitter</span></Button>
                  <Button size="lg" className="btn-linkedin icon"><span>LinkedIn</span></Button>
                  <Button size="lg" className="btn-flickr icon"><span>Flickr</span></Button>
                  <Button size="lg" className="btn-tumblr icon"><span>Tumblr</span></Button>
                  <Button size="lg" className="btn-xing icon"><span>Xing</span></Button>
                  <Button size="lg" className="btn-github icon"><span>Github</span></Button>
                  <Button size="lg" className="btn-html5 icon"><span>HTML5</span></Button>
                  <Button size="lg" className="btn-openid icon"><span>OpenID</span></Button>
                  <Button size="lg" className="btn-stack-overflow icon"><span>StackOverflow</span></Button>
                  <Button size="lg" className="btn-css3 icon"><span>CSS3</span></Button>
                  <Button size="lg" className="btn-youtube icon"><span>YouTube</span></Button>
                  <Button size="lg" className="btn-dribbble icon"><span>Dribbble</span></Button>
                  <Button size="lg" className="btn-google-plus icon"><span>Google+</span></Button>
                  <Button size="lg" className="btn-instagram icon"><span>Instagram</span></Button>
                  <Button size="lg" className="btn-pinterest icon"><span>Pinterest</span></Button>
                  <Button size="lg" className="btn-vk icon"><span>VK</span></Button>
                  <Button size="lg" className="btn-yahoo icon"><span>Yahoo</span></Button>
                  <Button size="lg" className="btn-behance icon"><span>Behance</span></Button>
                  <Button size="lg" className="btn-dropbox icon"><span>Dropbox</span></Button>
                  <Button size="lg" className="btn-reddit icon"><span>Reddit</span></Button>
                  <Button size="lg" className="btn-spotify icon"><span>Spotify</span></Button>
                  <Button size="lg" className="btn-vine icon"><span>Vine</span></Button>
                  <Button size="lg" className="btn-foursquare icon"><span>Forsquare</span></Button>
                  <Button size="lg" className="btn-vimeo icon"><span>Vimeo</span></Button>
                </p>
              </CardBlock>
            </Card>
          </Col>

          <Col xs="12">
            <Card>
              <CardHeader>
                <strong>Social Media Button</strong>
                <small>Only text. Usage ex.</small>
                <code style={{textTransform: 'lowercase'}}>&lt;button className="btn-facebook text"&gt;&lt;span&gt;
                  Facebook&lt;/span&gt;&lt;/Button&gt;</code>
              </CardHeader>
              <CardBlock className="card-body">
                <h6>Size Small
                  <small>Add this class <code>.btn-sm</code></small>
                </h6>
                <p>
                  <Button size="sm" className="btn-facebook text"><span>Facebook</span></Button>
                  <Button size="sm" className="btn-twitter text"><span>Twitter</span></Button>
                  <Button size="sm" className="btn-linkedin text"><span>LinkedIn</span></Button>
                  <Button size="sm" className="btn-flickr text"><span>Flickr</span></Button>
                  <Button size="sm" className="btn-tumblr text"><span>Tumblr</span></Button>
                  <Button size="sm" className="btn-xing text"><span>Xing</span></Button>
                  <Button size="sm" className="btn-github text"><span>Github</span></Button>
                  <Button size="sm" className="btn-html5 text"><span>HTML5</span></Button>
                  <Button size="sm" className="btn-openid text"><span>OpenID</span></Button>
                  <Button size="sm" className="btn-stack-overflow text"><span>StackOverflow</span></Button>
                  <Button size="sm" className="btn-css3 text"><span>CSS3</span></Button>
                  <Button size="sm" className="btn-youtube text"><span>YouTube</span></Button>
                  <Button size="sm" className="btn-dribbble text"><span>Dribbble</span></Button>
                  <Button size="sm" className="btn-google-plus text"><span>Google+</span></Button>
                  <Button size="sm" className="btn-instagram text"><span>Instagram</span></Button>
                  <Button size="sm" className="btn-pinterest text"><span>Pinterest</span></Button>
                  <Button size="sm" className="btn-vk text"><span>VK</span></Button>
                  <Button size="sm" className="btn-yahoo text"><span>Yahoo</span></Button>
                  <Button size="sm" className="btn-behance text"><span>Behance</span></Button>
                  <Button size="sm" className="btn-dropbox text"><span>Dropbox</span></Button>
                  <Button size="sm" className="btn-reddit text"><span>Reddit</span></Button>
                  <Button size="sm" className="btn-spotify text"><span>Spotify</span></Button>
                  <Button size="sm" className="btn-vine text"><span>Vine</span></Button>
                  <Button size="sm" className="btn-foursquare text"><span>Forsquare</span></Button>
                  <Button size="sm" className="btn-vimeo text"><span>Vimeo</span></Button>
                </p>
                <h6>Size Normal</h6>
                <p>
                  <Button className="btn-facebook text"><span>Facebook</span></Button>
                  <Button className="btn-twitter text"><span>Twitter</span></Button>
                  <Button className="btn-linkedin text"><span>LinkedIn</span></Button>
                  <Button className="btn-flickr text"><span>Flickr</span></Button>
                  <Button className="btn-tumblr text"><span>Tumblr</span></Button>
                  <Button className="btn-xing text"><span>Xing</span></Button>
                  <Button className="btn-github text"><span>Github</span></Button>
                  <Button className="btn-html5 text"><span>HTML5</span></Button>
                  <Button className="btn-openid text"><span>OpenID</span></Button>
                  <Button className="btn-stack-overflow text"><span>StackOverflow</span></Button>
                  <Button className="btn-css3 text"><span>CSS3</span></Button>
                  <Button className="btn-youtube text"><span>YouTube</span></Button>
                  <Button className="btn-dribbble text"><span>Dribbble</span></Button>
                  <Button className="btn-google-plus text"><span>Google+</span></Button>
                  <Button className="btn-instagram text"><span>Instagram</span></Button>
                  <Button className="btn-pinterest text"><span>Pinterest</span></Button>
                  <Button className="btn-vk text"><span>VK</span></Button>
                  <Button className="btn-yahoo text"><span>Yahoo</span></Button>
                  <Button className="btn-behance text"><span>Behance</span></Button>
                  <Button className="btn-dropbox text"><span>Dropbox</span></Button>
                  <Button className="btn-reddit text"><span>Reddit</span></Button>
                  <Button className="btn-spotify text"><span>Spotify</span></Button>
                  <Button className="btn-vine text"><span>Vine</span></Button>
                  <Button className="btn-foursquare text"><span>Forsquare</span></Button>
                  <Button className="btn-vimeo text"><span>Vimeo</span></Button>
                </p>
                <h6>Size Large
                  <small>Add this class <code>.btn-lg</code></small>
                </h6>
                <p>
                  <Button size="lg" className="btn-facebook text"><span>Facebook</span></Button>
                  <Button size="lg" className="btn-twitter text"><span>Twitter</span></Button>
                  <Button size="lg" className="btn-linkedin text"><span>LinkedIn</span></Button>
                  <Button size="lg" className="btn-flickr text"><span>Flickr</span></Button>
                  <Button size="lg" className="btn-tumblr text"><span>Tumblr</span></Button>
                  <Button size="lg" className="btn-xing text"><span>Xing</span></Button>
                  <Button size="lg" className="btn-github text"><span>Github</span></Button>
                  <Button size="lg" className="btn-html5 text"><span>HTML5</span></Button>
                  <Button size="lg" className="btn-openid text"><span>OpenID</span></Button>
                  <Button size="lg" className="btn-stack-overflow text"><span>StackOverflow</span></Button>
                  <Button size="lg" className="btn-css3 text"><span>CSS3</span></Button>
                  <Button size="lg" className="btn-youtube text"><span>YouTube</span></Button>
                  <Button size="lg" className="btn-dribbble text"><span>Dribbble</span></Button>
                  <Button size="lg" className="btn-google-plus text"><span>Google+</span></Button>
                  <Button size="lg" className="btn-instagram text"><span>Instagram</span></Button>
                  <Button size="lg" className="btn-pinterest text"><span>Pinterest</span></Button>
                  <Button size="lg" className="btn-vk text"><span>VK</span></Button>
                  <Button size="lg" className="btn-yahoo text"><span>Yahoo</span></Button>
                  <Button size="lg" className="btn-behance text"><span>Behance</span></Button>
                  <Button size="lg" className="btn-dropbox text"><span>Dropbox</span></Button>
                  <Button size="lg" className="btn-reddit text"><span>Reddit</span></Button>
                  <Button size="lg" className="btn-spotify text"><span>Spotify</span></Button>
                  <Button size="lg" className="btn-vine text"><span>Vine</span></Button>
                  <Button size="lg" className="btn-foursquare text"><span>Forsquare</span></Button>
                  <Button size="lg" className="btn-vimeo text"><span>Vimeo</span></Button>
                </p>
              </CardBlock>
            </Card>
          </Col>
        </Row>
      </div>

    )
  }
}

export default SocialButtons;
